apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: kubens
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: "1"
    defaultRequest:
      memory: 250Mi
      cpu: "0.5"
    type: Container
