apiVersion: v1
kind: Pod
metadata:
  name: multihost
  labels:
    app: web-host
spec: 
  containers:
    - name: tomcat
      image: tomcat:9.0
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80


        
